.TH "jpegcshrink" 1 "23 Jan 2020" "0.1.0" "User Manual"

.SH NAME
jpegcshrink

.SH SYNOPSIS
\fBjpegcshrink\fR [options] input.jpg output.jpg

.SH DESCRIPTION
JPEG DCT coefficients access in C. Shrink JPEG DCT coefficients.

.SH OPTIONS
.TP
\fB-c\fR N
count cicle (int, optional, default = 1)
.TP
\fB-d\fR N
delta coeff (default = 0);
.TP
\fB-l\fR N
lower bound (int, optional, default = 0)
.TP
\fB-u\fR N
upper bound (int, optional, default = max)
.TP
\fB-h\fR
help

.SH EXAMPLE
\fBjpegcshrink\fR -d 5 -l 5 sample.jpg sample.js5l5.jpg

.SH COPYRIGHT
 Copyright (C) 2012, Owen Campbell-Moore.
 Modify 2019-2020, zvezdochiot
 Public Domain Mark 1.0

.SH SEE ALSO
 cjpeg(1),
 djpeg(1),
 jpegquant(1),
 jpegcstat(1),
 jpeg-recompress(1).

.SH CONTACTS
Website:
 \fIhttps://github.com/ImageProcessing-ElectronicPublications/jpegquant\fR

