.TH "jpegquant" 1 "01 Feb 2020" "0.1.1" "User Manual"

.SH NAME
jpegquant

.SH SYNOPSIS
\fBjpegquant\fR [options] input.jpg output.jpg

.SH DESCRIPTION
JPEG DCT coefficients access in C. Quant JPEG DCT coefficients.

.SH OPTIONS
.TP
\fB-c\fR N
count cicle (int, optional, default = 1)
.TP
\fB-l\fR N
lower bound (int, optional, default = 0)
.TP
\fB-u\fR N
upper bound (int, optional, default = max)
.TP
\fB-k\fR N.N
coeff average (default = 1.0);
.TP
\fB-q\fR N.N
quant (default = 1.0);
.TP
\fB-t\fR N.N
threshold (default = 0.0);
.TP
\fB-h\fR
help

.SH EXAMPLE
\fBjpegquant\fR -q 2 sample.jpg sample.jq2.jpg

.SH COPYRIGHT
 Copyright (C) 2012, Owen Campbell-Moore.
 Modify 2019-2020, zvezdochiot
 Public Domain Mark 1.0

.SH SEE ALSO
 cjpeg(1),
 djpeg(1),
 jpegcshrink(1),
 jpegcstat(1),
 jpegquarel(1),
 jpeg-recompress(1).

.SH CONTACTS
Website:
 \fIhttps://github.com/ImageProcessing-ElectronicPublications/jpegquant\fR

