.TH "jpegquarel" 1 "04 Feb 2020" "0.2.2" "User Manual"

.SH NAME
jpegquarel

.SH SYNOPSIS
\fBjpegquant\fR [options] input.jpg output.jpg

.SH DESCRIPTION
JPEG DCT coefficients access in C. Relative quant JPEG DCT coefficients.

.SH OPTIONS
.TP
\fB-c\fR N
count cicle (int, optional, default = 1)
.TP
\fB-k\fR N.N
coeff average (default = 1.0);
.TP
\fB-l\fR N
lower bound (int, optional, default = 0)
.TP
\fB-u\fR N
upper bound (int, optional, default = max)
.TP
\fB-d\fR N.N
rounding quant (default = 0.5)
.TP
\fB-q\fR N.N
quant (default = 1.0);
.TP
\fB-h\fR
help

.SH EXAMPLE
\fBjpegquarel\fR -q 3 sample.jpg sample.jqr3.jpg

.SH COPYRIGHT
 Copyright (C) 2012, Owen Campbell-Moore.
 Modify 2019-2020, zvezdochiot
 Public Domain Mark 1.0

.SH SEE ALSO
 cjpeg(1),
 djpeg(1),
 jpegcshrink(1),
 jpegcstat(1),
 jpegquant(1),
 jpeg-recompress(1).

.SH CONTACTS
Website:
 \fIhttps://github.com/ImageProcessing-ElectronicPublications/jpegquant\fR
