.TH "jpegcstat" 1 "01 Feb 2020" "0.1.1" "User Manual"

.SH NAME
jpegcstat

.SH SYNOPSIS
\fBjpegcstat\fR [options] input.jpg

.SH DESCRIPTION
JPEG DCT coefficients access in C. Histogram statistic JPEG DCT coefficients.

.SH OPTIONS
.TP
\fB-l\fR N
lower bound (int, optional, default = 0)
.TP
\fB-u\fR N
upper bound (int, optional, default = max)
.TP
\fB-h\fR
help

.SH EXAMPLE
\fBjpegcstat\fR sample.jpg

.SH COPYRIGHT
 Copyright (C) 2012, Owen Campbell-Moore.
 Modify 2019-2020, zvezdochiot
 Public Domain Mark 1.0

.SH SEE ALSO
 cjpeg(1),
 djpeg(1),
 jpegcshrink(1),
 jpegquant(1),
 jpegquarel(1),
 jpeg-recompress(1).

.SH CONTACTS
Website:
 \fIhttps://github.com/ImageProcessing-ElectronicPublications/jpegquant\fR

